import { Pokemon } from './pokemon';

export const POKEMONS: Pokemon[] = 
 [
  {
    "name": "bulbasaur",
    "id": 1,
    "captured": false,
    "damage": 0,
    "description": "Lorem ipsum dolor sit amet",
    "date": new Date(),
  },
  {
    "name": "ivysaur",
    "id": 2,
    "captured": false,
    "damage": 0,
    "description": "Lorem ipsum dolor sit amet",
    "date": new Date(),
  },
  {
    "name": "venusaur",
    "id": 3,
    "captured": false,
    "damage": 0,
    "description": "Lorem ipsum dolor sit amet",
    "date": new Date(),
  },
  {
    "name": "charmander",
    "id": 4,
    "captured": false,
    "damage": 0,
    "description": "Lorem ipsum dolor sit amet",
    "date": new Date(),
  },
  {
    "name": "charmeleon",
    "id": 5,
    "captured": false,
    "damage": 0,
    "description": "Lorem ipsum dolor sit amet",
    "date": new Date(),
  },
  {
    "name": "charizard",
    "id": 6,
    "captured": false,
    "damage": 0,
    "description": "Lorem ipsum dolor sit amet",
    "date": new Date(),
  },
  {
    "name": "squirtle",
    "id": 7,
    "captured": false,
    "damage": 0,
    "description": "Lorem ipsum dolor sit amet",
    "date": new Date(),
  },
  {
    "name": "wartortle",
    "id": 8,
    "captured": false,
    "damage": 0,
    "description": "Lorem ipsum dolor sit amet",
    "date": new Date(),
  },
  {
    "name": "blastoise",
    "id": 9,
    "captured": false,
    "damage": 0,
    "description": "Lorem ipsum dolor sit amet",
    "date": new Date(),
  },
  {
    "name": "caterpie",
    "id": 10,
    "captured": false,
    "damage": 0,
    "description": "Lorem ipsum dolor sit amet",
    "date": new Date(),
  },
  {
    "name": "metapod",
    "id": 11,
    "captured": false,
    "damage": 0,
    "description": "Lorem ipsum dolor sit amet",
    "date": new Date(),
  },
  {
    "name": "butterfree",
    "id": 12,
    "captured": false,
    "damage": 0,
    "description": "Lorem ipsum dolor sit amet",
    "date": new Date(),
  },
]